import '@/styles/globals.css';
import { Metadata } from 'next';
import Providers from './Providers';
import RootLayoutWrapper from '@/components/common/RootLayout/RootLayoutWrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="kr">
      <body>
        <RootLayoutWrapper>
          <Providers>{children}</Providers>
        </RootLayoutWrapper>
      </body>
    </html>
  );
}
