FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
# RUN pnpm run -r build
RUN pnpm --filter="web-app web-event" run build
# RUN pnpm app build
# RUN pnpm event build
RUN pnpm deploy --filter=web-app --prod /prod/web-app
RUN pnpm deploy --filter=web-event --prod /prod/web-event

FROM base AS web-app
COPY --from=build /prod/web-app /prod/web-app
WORKDIR /prod/web-app
EXPOSE 3000
CMD [ "pnpm", "start" ]

FROM base AS web-event
COPY --from=build /prod/web-event /prod/web-event
WORKDIR /prod/web-event
EXPOSE 3000
CMD [ "pnpm", "start" ]
