import type { Metadata } from 'next';
import './globals.css';
import { RootLayoutWrapper } from 'common';

// import dynamic from 'next/dynamic';
// const RootLayoutWrapper = dynamic(
//   () => import('common').then((mode) => mode.RootLayoutWrapper),
//   {
//     loading: () => <p>Loading...</p>,
//     ssr: false,
//   },
// );

export const metadata: Metadata = {
  title: {
    template: '%s - template',
    default: 'Next',
    // absolute: '...',
  },
  description: 'Generated by create next app',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootLayoutWrapper>{children}</RootLayoutWrapper>
      </body>
    </html>
  );
}
